apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels: 
    type: local
spec:
  storageClassName: localstorage
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/mongodb
