apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: mycontainer
    image: mmumshad/simple-webapp-color:latest
    env:
    - name: COLOR
      valueFrom: 
        configMapKeyRef:
          name: my-config
          key: APP_COLOR
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    ports:
    - containerPort: 8080
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}

