apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    purpose: demonstrate-envars
spec:
  containers:
    - image: mmumshad/simple-webapp-color:latest
      name: mypod
      volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true
      ports:
        - containerPort: 8080
  volumes:
    - name: foo
      secret:
        secretName: mysecret
  
         
     