apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: lab3
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: mypod
    image: mmumshad/simple-webapp-color:latest
    env:
    - name: APP_COLOR
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: APP_COLOR
    ports:
    - containerPort: 8080
