apiVersion: v1
kind: Pod
metadata:
  name: myconfigmap
spec:
  containers:
  - image: mmumshad/simple-webapp-color:latest
    env:
    - name: APP_COLOR
      valueFrom: 
        configMapKeyRef:
          name: fortune-config
          key: APP_COLOR
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
