apiVersion: v1
kind: Pod
metadata:
  name: app-env
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: mmumshad/simple-webapp-color:latest
    env:
    - name: APP_COLOR
      value: "blue"
    ports:
    - containerPort: 8080